version: "3.8"

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/myapp
    environment:
      - RUST_LOG=info
    command: cargo run