name: CI Example

# When to run
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# Define what to do
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1 # Use the latest version
      with:
        toolchain: stable # Or specify a version like 1.70.0
        # components: rustfmt, clippy # Optional: Install additional components
        # targets: x86_64-pc-windows-gnu # Optional: Install targets for cross-compilation
    - name: Run tests
      run: cargo test